<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>SamplePlugin</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <!-- Core is loaded by the host; don't copy to plugin output -->
    <ProjectReference Include="..\..\Core\POPYBot.Core.csproj" Private="false" />
  </ItemGroup>

</Project>
